# Generated by Django 2.2.5 on 2019-10-21 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('num_gafas', models.IntegerField(default=0)),
                ('aforo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clase', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_personas', models.IntegerField(default=0)),
                ('num_gafas', models.IntegerField(default=0)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('incio_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('final_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VR.Aula')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gafas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VR.Aula')),
            ],
        ),
    ]
