# Generated by Django 2.2.5 on 2019-10-21 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VR', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gafas',
            new_name='Gafa',
        ),
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Reserva',
        ),
    ]
